#server:
#  port: 8761
spring:
  application:
    name: eureka
eureka:
  server:
    enable-self-preservation: false
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    #禁止自己当做服务注册
    #屏蔽注册信息
#    register-with-eureka: false
#management:
#  server:
#    servlet:
#      context-path: /
